dataset_path: lmms-lab/MMMU
task: "mmmu_val"
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.mmmu_doc_to_visual
doc_to_text: !function utils.mmmu_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.mmmu_process_results

metric_list:
  - metric: mmmu_acc
    aggregation: !function utils.mmmu_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    prompt_type: "format"
    multiple_choice_prompt: "Answer with the option's letter from the given choices directly."
    open_ended_prompt: "Answer the question using a single word or phrase."
  llava_v6:
    prompt_type: "format"
    multiple_choice_prompt: "For the given Multiple Choice Question Answer below, analyze the question and answer strictly from one of the options below. End your answer with 'Final Answer: <your answer>' where <your answer> is strictly the option letter from the given choices only."
    open_ended_prompt: "For the given Question, analyze the question and answer strictly using a single word or phrase. End your answer with 'Final Answer: <your answer>' where <your answer> is strictly the final answer (a single word or phrase) only."

include: _default_template_yaml