# if comparative, then the judge will compare the baseline model output with the predicted outputs. If the baseline model outputs path is not found, then the predicted outputs will be just saved, without running the judge.
# if direct assessment, then the judge will just judge the predicted outputs!
# to disable the judge, set run_judge to false
run_judge: false
api_type: openai #openai #anthropic
judge_model_name: gpt-4o-mini #gpt-4o-mini #claude-3-7-sonnet-20250219
judge_prompt_type: comparative
text_only: true
baseline_model_outputs_path: /mnt/scratch-artemis/manos/data/tower-vision-eval-outputs/tower-vision/tower-vision-debug-results/aya-vision-bench-gen-eng/Unbabel__lnext-qwen2p5-7b-siglip2-v5/Unbabel__lnext-qwen2p5-7b-siglip2-v5/20250416_060306_samples_aya-vision-bench-gen-eng.jsonl
max_tokens: 1024
temperature: 0
api_url: https://api.openai.com/v1/chat/completions    #https://api.anthropic.com/v1/messages  for anthropic